name: Flatpak

on:
  pull_request:
    types: [ closed ]

jobs:
  flatpak:
    if: github.event.pull_request.merged == true
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      with:
        manifest-path: package/gui.flatpak.json
        bundle: cash.pkt.desktop.flatpak
        cache-key: flatpak-builder-${{ github.workflow }}-${{ github.ref }}
    - uses: actions/upload-artifact@v2
      with:
        path: cash.pkt.desktop.flatpak
