name: Flatpak

on:
  pull_request:
    types: [ closed ]

jobs:
  flatpak:
    if: github.event.pull_request.merged == true
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.4
      options: --privileged
    steps:
    - name: Get more disk space
      run: |
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "${JAVA_HOME_8_X64}"
        sudo rm -rf "${JAVA_HOME_11_X64}"
      shell: bash
      continue-on-error: true
    - name: Checkout metier
      uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        submodules: 'recursive'
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v5
      with:
        manifest-path: package/gui.flatpak.json
        bundle: org.opentransactions.metier.flatpak
    - uses: actions/upload-artifact@v2
      with:
        path: org.opentransactions.metier.flatpak
